import{NewGlyphCandidate,generateNewGlyphVocabulary,renderNewGlyphSvg}from"./new-glyph-system";
export type CompoundForm="flower"|"orbit"|"branch"|"crown"|"guardian"|"flight";
export type PhraseMeaning="root"|"lineage"|"path"|"protection"|"transformation"|"flowering"|"flight"|"ascent"|"integration"|"return";
export interface CompoundGlyph{id:string;seed:string;form:CompoundForm;members:NewGlyphCandidate[];relation:"radial"|"bilateral"|"nested"|"ascending"|"orbiting";provenance:{kind:"original-synthesis";legacyAtlasRequired:false;copiedHistoricalMotif:false}}
export interface GlyphPhrase{id:string;seed:string;meaning:PhraseMeaning;compounds:CompoundGlyph[];cadence:"continuous"|"alternating"|"threshold"|"crescendo"|"returning"}
const F:CompoundForm[]=["flower","orbit","branch","crown","guardian","flight"],R:CompoundGlyph["relation"][]=["radial","bilateral","nested","ascending","orbiting"],C:GlyphPhrase["cadence"][]=["continuous","alternating","threshold","crescendo","returning"];
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
export function buildCompoundGlyph(seed:string,index=0,members=5):CompoundGlyph{if(members<2||members>12)throw new Error("members must be 2-12");const h=hash(seed+"|compound|"+index),v=generateNewGlyphVocabulary(seed+"|compound-vocab",108),selected=Array.from({length:members},(_,i)=>v[(h+i*17)%v.length]!);return{id:`asc-comp-${String(index+1).padStart(3,"0")}`,seed:`${seed}|compound|${index}`,form:F[h%F.length]!,members:selected,relation:R[(h>>>4)%R.length]!,provenance:{kind:"original-synthesis",legacyAtlasRequired:false,copiedHistoricalMotif:false}}}
export function buildGlyphPhrase(seed:string,meaning:PhraseMeaning,count=4):GlyphPhrase{if(count<2||count>16)throw new Error("count must be 2-16");const h=hash(seed+"|"+meaning);return{id:`asc-phrase-${meaning}-${(h%10000).toString().padStart(4,"0")}`,seed,meaning,compounds:Array.from({length:count},(_,i)=>buildCompoundGlyph(seed+"|"+meaning,i,3+(h+i)%6)),cadence:C[(h>>>5)%C.length]!}}
export function renderCompoundSvg(c:CompoundGlyph):string{const n=c.members.length,items=c.members.map((g,i)=>{const a=i/n*Math.PI*2,r=c.relation==="nested"?i*3:18+(i%2)*6,x=50+r*Math.cos(a),y=50+r*Math.sin(a),scale=c.relation==="nested"?.25+i*.035:.28;const inner=renderNewGlyphSvg(g).replace(/^<svg[^>]*>|<\/svg>$/g,"");return `<g transform="translate(${x.toFixed(2)} ${y.toFixed(2)}) rotate(${(a*180/Math.PI+90).toFixed(1)}) scale(${scale}) translate(-50 -50)">${inner}</g>`}).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><metadata>${JSON.stringify({id:c.id,form:c.form,relation:c.relation,memberIds:c.members.map(x=>x.id),provenance:c.provenance})}</metadata>${items}</svg>`}
export function renderPhraseSvg(p:GlyphPhrase):string{const n=p.compounds.length,items=p.compounds.map((c,i)=>{const inner=renderCompoundSvg(c).replace(/^<svg[^>]*>|<\/svg>$/g,""),x=8+i*(84/Math.max(1,n-1)),s=p.cadence==="crescendo"?.35+i*.06:.42;return `<g transform="translate(${x.toFixed(2)} 50) scale(${s.toFixed(3)}) translate(-50 -50)">${inner}</g>`}).join("");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><metadata>${JSON.stringify({id:p.id,meaning:p.meaning,cadence:p.cadence,compoundIds:p.compounds.map(x=>x.id)})}</metadata>${items}</svg>`}
