import{GlyphPhrase,renderPhraseSvg}from"./compound-language";
export type BandMode="continuous"|"alternating"|"mirrored"|"threshold";
export type MacroForm="axis"|"tree"|"crown"|"orbit"|"wings"|"return-loop";
export interface PhraseBand{id:string;phraseId:string;mode:BandMode;repeats:number;phase:number;negativeSpace:number}
export interface PhraseField{id:string;bands:PhraseBand[];macroForm:MacroForm;microDensity:number;macroPath:{x:number;y:number}[];semanticChecksum:string}
const hash=(s:string)=>{let h=2166136261;for(const c of s){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
const checksum=(s:string)=>hash(s).toString(16).padStart(8,"0");
export function composeBand(p:GlyphPhrase,index=0):PhraseBand{const h=hash(p.seed+"|band|"+index),m:BandMode[]=["continuous","alternating","mirrored","threshold"];return{id:`${p.id}-band-${index+1}`,phraseId:p.id,mode:m[h%4],repeats:5+(h%12),phase:(h>>>5)%360,negativeSpace:Number((.18+((h>>>9)%35)/100).toFixed(2))}}
export function composeField(phrases:GlyphPhrase[],seed:string,bandsPerPhrase=2):PhraseField{if(!phrases.length)throw new Error("phrases required");const h=hash(seed),forms:MacroForm[]=["axis","tree","crown","orbit","wings","return-loop"],bands=phrases.flatMap((p,i)=>Array.from({length:bandsPerPhrase},(_,j)=>composeBand(p,i*bandsPerPhrase+j))),macroForm=forms[h%forms.length],macroPath=Array.from({length:24},(_,i)=>{const t=i/23,a=t*Math.PI*2;switch(macroForm){case"orbit":return{x:50+34*Math.cos(a),y:50+34*Math.sin(a)};case"wings":return{x:50+38*Math.sin(a)*Math.sin(a),y:10+t*80};case"return-loop":return{x:50+28*Math.sin(a),y:50+28*Math.sin(a*2)};case"crown":return{x:10+t*80,y:58-26*Math.abs(Math.sin(a*1.5))};case"tree":return{x:50+22*Math.sin(a)*t,y:90-t*80};default:return{x:50+5*Math.sin(a*3),y:90-t*80}}});return{id:`asc-field-${checksum(seed)}`,bands,macroForm,microDensity:Number((.55+(h%31)/100).toFixed(2)),macroPath,semanticChecksum:checksum(phrases.map(p=>p.id+":"+p.meaning).join("|"))}}
export function renderFieldSvg(field:PhraseField,phrases:GlyphPhrase[]):string{const phraseMap=new Map(phrases.map(p=>[p.id,p]));const rows=field.bands.map((b,i)=>{const p=phraseMap.get(b.phraseId);if(!p)return"";const inner=renderPhraseSvg(p).replace(/^<svg[^>]*>|<\/svg>$/g,""),y=8+i*(84/Math.max(1,field.bands.length-1));return Array.from({length:b.repeats},(_,j)=>{const x=(j+.5)*100/b.repeats,s=.18+(1-b.negativeSpace)*.12,flip=b.mode==="mirrored"&&j%2?-1:1;return `<g transform="translate(${x.toFixed(2)} ${y.toFixed(2)}) scale(${(s*flip).toFixed(3)} ${s.toFixed(3)}) translate(-50 -50)">${inner}</g>`}).join("")}).join("");const path=field.macroPath.map((p,i)=>`${i?"L":"M"}${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(" ");return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" data-semantic-checksum="${field.semanticChecksum}"><path d="${path}" fill="none" stroke="currentColor" stroke-opacity=".10" stroke-width="1"/>${rows}</svg>`}
