import type {SynthesisIntent} from "./core";
import type {Grammar,GrammarRule,PrimitiveKind} from "./grammar";

export interface UniversalFeature{ruleId:string;primitive:PrimitiveKind;path:string}
export interface UniversalCandidate{id:string;seed:string;viewBox:"0 0 1000 1000";features:UniversalFeature[];svg:string;recipe:{version:"0.1";seed:string;meanings:string[];principleIds:string[];density:SynthesisIntent["density"];symmetry:SynthesisIntent["symmetry"];ruleIds:string[]}}
const h=(s:string)=>{let x=2166136261;for(const c of s){x^=c.charCodeAt(0);x=Math.imul(x,16777619)}return x>>>0};
const f=(n:number)=>Number(n.toFixed(2));
function choose(intent:SynthesisIntent,g:Grammar):GrammarRule[]{const n=intent.density==="restrained"?3:intent.density==="complex"?7:5,r=[...g.rules].sort((a,b)=>b.weight-a.weight||a.id.localeCompare(b.id)),out:GrammarRule[]=[];if(!r.length)return out;const seed=h(intent.seed+"|"+intent.meanings.join("|")+"|"+intent.principleIds.join("|"));for(let i=0;i<r.length&&out.length<Math.min(n,r.length);i++){const x=r[(seed+i*5)%r.length];if(x&&!out.some(y=>y.id===x.id))out.push(x)}return out}
function path(p:PrimitiveKind,i:number,n:number){const cx=500,y=120+(760*(i+1))/(n+1),d=90+22*i;if(p==="axis")return"M500 80 V920";if(p==="enclosure")return"M100 100 H900 V900 H100 Z";if(p==="branch")return`M500 ${f(y)} L${500-d} ${f(y-70)} M500 ${f(y)} L${500+d} ${f(y-70)}`;if(p==="step")return`M${500-d} ${f(y)} H500 V${f(y-55)} H${500+d}`;if(p==="chevron")return`M${500-d} ${f(y+45)} L500 ${f(y-45)} L${500+d} ${f(y+45)}`;if(p==="band")return`M120 ${f(y-22)} H880 M120 ${f(y+22)} H880`;if(p==="lattice")return`M${500-d} ${f(y-50)} L${500+d} ${f(y+50)} M${500-d} ${f(y+50)} L${500+d} ${f(y-50)}`;if(p==="meander")return`M${500-d} ${f(y)} H${500-d/2} V${f(y-45)} H${500+d/2} V${f(y+45)} H${500+d}`;if(p==="rosette")return`M${500-d/2} ${f(y)} A${d/2} ${d/2} 0 1 0 ${500+d/2} ${f(y)} A${d/2} ${d/2} 0 1 0 ${500-d/2} ${f(y)}`;return`M${500-d} ${f(y)} L${500-d/2} ${f(y-35)} L500 ${f(y)} L${500+d/2} ${f(y+35)} L${500+d} ${f(y)}`}
export function synthesizeUniversal(intent:SynthesisIntent,grammar:Grammar):UniversalCandidate{if(!intent.seed.trim()||!intent.meanings.length||!intent.principleIds.length)throw new Error("seed, meanings and evidence-backed principles required");const rules=choose(intent,grammar);if(!rules.length)throw new Error("audited grammar has no eligible rules");const features=rules.map((r,i)=>({ruleId:r.id,primitive:r.primitive,path:path(r.primitive,i,rules.length)}));const body=features.map(x=>`<path data-rule="${x.ruleId}" d="${x.path}"/>`).join("");const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" fill="none" stroke="currentColor" stroke-width="6"><g>${body}</g></svg>`;return{id:`universal-${h(intent.seed+"|"+rules.map(x=>x.id).join("|")).toString(16)}`,seed:intent.seed,viewBox:"0 0 1000 1000",features,svg,recipe:{version:"0.1",seed:intent.seed,meanings:[...intent.meanings],principleIds:[...intent.principleIds],density:intent.density,symmetry:intent.symmetry,ruleIds:rules.map(x=>x.id)}}}
