import type{Topology}from"./topology";
import type{LegoBlock}from"./pattern-lego-grammar";
export interface CompositionScore{hierarchy:number;rhythm:number;balance:number;surprise:number;coherence:number;negativeSpace:number;scaleSurvival:number;originality:number;total:number}
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
export function scoreComposition(blocks:LegoBlock[]):CompositionScore{if(!blocks.length)return{hierarchy:0,rhythm:0,balance:0,surprise:0,coherence:0,negativeSpace:0,scaleSurvival:0,originality:0,total:0};const families=new Set(blocks.map(b=>b.family)).size/blocks.length;const roles=new Set(blocks.flatMap(b=>b.semanticRoles)).size/Math.max(1,blocks.length);const sockets=blocks.reduce((n,b)=>n+b.sockets.length,0)/blocks.length;const nested=blocks.filter(b=>b.children?.length).length/blocks.length;const mutation=blocks.reduce((n,b)=>n+b.mutation,0)/blocks.length;const s={hierarchy:clamp(.45+nested*.55),rhythm:clamp(.5+sockets*.08),balance:clamp(.75-Math.abs(.2-mutation)),surprise:clamp(.35+mutation+families*.25),coherence:clamp(.85-families*.2+roles*.1),negativeSpace:clamp(.4+blocks.filter(b=>b.sockets.some(s=>s.kind==="void")).length/blocks.length*.5),scaleSurvival:clamp(.5+nested*.4),originality:clamp(.45+families*.25+mutation)};return{...s,total:Object.values(s).reduce((a,b)=>a+b,0)/8}}
export function rankCompositions<T extends{blocks:LegoBlock[]}>(c:T[]){return c.map(x=>({candidate:x,score:scoreComposition(x.blocks)})).sort((a,b)=>b.score.total-a.score.total)}

const socketKind=(relation:string):import("./pattern-lego-grammar").SocketKind=>relation==="branch"?"branch":relation==="radiate"?"radial":relation==="return"||relation==="orbit"?"loop":relation==="terminate"?"void":relation==="flow"||relation==="ascend"?"stem":"edge";
export function blocksFromTopology(t:Topology):LegoBlock[]{return t.nodes.map(n=>{const attached=t.edges.filter(e=>e.from===n.id||e.to===n.id);const transformLoad=attached.filter(e=>["transform","intersect","oppose","terminate"].includes(e.relation)).length/Math.max(1,attached.length);const sockets=attached.map((e,i)=>({id:`${n.id}:s${i}`,kind:socketKind(e.relation),polarity:e.from===n.id?"out" as const:"in" as const,x:e.from===n.id?1:0,y:(i+1)/(attached.length+1),angle:e.from===n.id?0:180,tolerance:35,scaleMin:.25,scaleMax:4,tags:[e.relation]}));if(n.form==="void")sockets.push({id:`${n.id}:void`,kind:"void",polarity:"either",x:.5,y:.5,angle:0,tolerance:180,scaleMin:.25,scaleMax:4,tags:["negative-space"]});return{id:n.id,family:n.form,sourceInstanceIds:[],semanticRoles:[n.conceptId],symmetry:"none",mutation:clamp(.08+transformLoad*.55),sockets,children:n.scale>=3?[{blockId:n.id,x:0,y:0,rotation:0,scale:.5}]:undefined}})}
export function scoreTopologyComposition(t:Topology){return scoreComposition(blocksFromTopology(t))}
