export type AscendPrimitive="seed"|"diamond"|"fork"|"hook"|"ring"|"step"|"crossing"|"petal"|"wave";
export type AscendOperation="echo"|"mirror"|"interlock"|"branch"|"nest"|"interrupt"|"drift"|"bloom"|"bind";
export interface AscendSentence{seed:string;meaning:string;intensity?:number;continuity?:number;reciprocity?:number;operations?:string[];topology?:string;closure?:string;rhythm?:string}
export interface AscendGrammar{primitives:AscendPrimitive[];operations:AscendOperation[];density:number;variation:number;hierarchy:number}
const h=(s:string)=>{let n=2166136261;for(const c of s){n^=c.charCodeAt(0);n=Math.imul(n,16777619)}return n>>>0};
export function deriveAscendGrammar(s:AscendSentence):AscendGrammar{const n=h(s.seed+"|"+s.meaning+"|"+(s.operations??[]).join(",")+"|"+(s.topology??"")+"|"+(s.rhythm??""));const semantic=(s.operations??[]).map(x=>({approach:"drift",bind:"bind",mirror:"mirror",enclose:"nest",continue:"echo",branch:"branch",expand:"bloom",converge:"bind",interrupt:"interrupt",resume:"echo",alternate:"mirror",open:"drift",inherit:"nest",transform:"interlock"}[x])).filter(Boolean) as AscendOperation[];return{primitives:["seed","diamond","fork","hook","ring","step","crossing","petal","wave"],operations:[...new Set<AscendOperation>([...semantic,"echo","mirror","interlock","branch","nest","interrupt","drift","bloom","bind"])],density:.62+((n&15)/100),variation:.24+(((n>>4)&15)/100),hierarchy:.78}}
function unit(kind:AscendPrimitive,x:number,y:number,z:number){const q=z/4,m=z/2;switch(kind){case"diamond":return `M${x+m} ${y}L${x+z} ${y+m} ${x+m} ${y+z} ${x} ${y+m}Z`;case"ring":return `M${x+m-q} ${y+m}a${q} ${q} 0 1 0 ${q*2} 0a${q} ${q} 0 1 0 -${q*2} 0`;case"fork":return `M${x+m} ${y+z}V${y+q}M${x+m} ${y+m}L${x+q} ${y+q}M${x+m} ${y+m}L${x+z-q} ${y+q}`;case"hook":return `M${x+q} ${y+q}H${x+z-q}V${y+m}H${x+m}V${y+z-q}`;case"step":return `M${x} ${y+z-q}H${x+q}V${y+m}H${x+m}V${y+q}H${x+z}`;case"crossing":return `M${x+q} ${y+q}L${x+z-q} ${y+z-q}M${x+z-q} ${y+q}L${x+q} ${y+z-q}`;case"petal":return `M${x+m} ${y+z-q}Q${x} ${y+m} ${x+m} ${y+q}Q${x+z} ${y+m} ${x+m} ${y+z-q}`;case"wave":return `M${x} ${y+m}Q${x+q} ${y} ${x+m} ${y+m}T${x+z} ${y+m}`;default:return `M${x+m} ${y+q}L${x+z-q} ${y+z-q}L${x+q} ${y+z-q}Z`}}
const fmt=(n:number)=>Number(n.toFixed(2));
function curvePath(seed:string,w:number,hgt:number,topology:string|undefined,index:number){const n=h(seed+"|curve|"+index),phase=((n>>>8)%628)/100,amp=hgt*(.08+((n>>>16)%14)/100),base=hgt*(.22+index*.14);let d="";for(let i=0;i<=18;i++){const t=i/18,x=t*w,y=topology==="radial"?hgt/2+Math.sin(t*Math.PI*2+phase)*(hgt*.18+index*4):topology==="enclosure"?hgt/2+Math.sin(t*Math.PI*2+phase)*hgt*.34:base+Math.sin(t*Math.PI*2*(1.15+index*.12)+phase)*amp;d+=(i?"L":"M")+fmt(x)+" "+fmt(y)}return d}
export function renderAscendSentence(s:AscendSentence,w=1200,hgt=360){const g=deriveAscendGrammar(s),paths:string[]=[];const curves=3+Math.round(g.hierarchy*4);for(let i=0;i<curves;i++){const spine=curvePath(s.seed+"|"+s.meaning,w,hgt,s.topology,i);paths.push(spine);const n=h(s.seed+"|ornament|"+i);const count=18+((n>>>4)%20);for(let j=1;j<count;j++){const t=j/count,x=t*w,phase=((n>>>8)%628)/100,base=hgt*(.22+i*.14),amp=hgt*(.08+((n>>>16)%14)/100),y=base+Math.sin(t*Math.PI*2*(1.15+i*.12)+phase)*amp;const r=3+((h(s.seed+"|"+i+"|"+j)>>>6)%7),side=j%2?1:-1;paths.push(`M${fmt(x)} ${fmt(y)}q${fmt(r*1.8)} ${fmt(-side*r*2.6)} ${fmt(r*3.6)} 0q${fmt(-r*1.8)} ${fmt(side*r*2.6)} ${fmt(-r*3.6)} 0`);if(j%3===0)paths.push(`M${fmt(x)} ${fmt(y)}l${fmt(side*r*1.6)} ${fmt(-r*2.8)}l${fmt(side*r*1.6)} ${fmt(r*2.8)}`)} }
const cx=w/2,cy=hgt/2;for(let k=0;k<7;k++){const n=h(s.seed+"|focus|"+k),a=(k/7)*Math.PI*2,r=hgt*(.08+k*.018),x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r,pet=5+(n%4);let d="";for(let p=0;p<=pet*2;p++){const aa=(p/(pet*2))*Math.PI*2,rr=p%2?r*.18:r*.42;d+=(p?"L":"M")+fmt(x+Math.cos(aa)*rr)+" "+fmt(y+Math.sin(aa)*rr)}paths.push(d+"Z")}
return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${hgt}" data-language="ascend-universal-v2" data-renderer="continuous-multiscale"><metadata>${JSON.stringify({meaning:s.meaning,seed:s.seed,topology:s.topology,operations:s.operations??[],copyHistoricalGeometry:false})}</metadata><g fill="none" stroke="currentColor" stroke-width="1.55" stroke-linecap="round" stroke-linejoin="round"><path d="${paths.join("")}"/></g></svg>`}
