import type{CulturalCorpusRecord,FeatureFamily}from"./cultural-analysis";
export type UniversalPrimitive="point"|"line"|"crossing"|"angle"|"step"|"hook"|"wave"|"spiral"|"ring"|"diamond"|"radial"|"branch"|"lattice"|"enclosure";
export type Relation="repeat"|"alternate"|"mirror"|"rotate"|"nest"|"interlock"|"branch"|"border"|"center"|"interrupt"|"expand"|"contract";
export interface MorphologyObservation{recordId:string;cultureId:string;primitive:UniversalPrimitive;relation:Relation;weight:number;sourceIds:string[]}
export interface Invariant{primitive:UniversalPrimitive;relation:Relation;cultures:string[];sources:string[];support:number;diversity:number}
export function discoverInvariants(obs:MorphologyObservation[],minCultures=3):Invariant[]{const m=new Map<string,MorphologyObservation[]>();for(const o of obs){const k=o.primitive+"|"+o.relation;m.set(k,[...(m.get(k)??[]),o])}return[...m.entries()].map(([k,x])=>{const[primitive,relation]=k.split("|") as[UniversalPrimitive,Relation],cultures=[...new Set(x.map(o=>o.cultureId))],sources=[...new Set(x.flatMap(o=>o.sourceIds))];return{primitive,relation,cultures,sources,support:x.reduce((n,o)=>n+o.weight,0),diversity:cultures.length}}).filter(x=>x.diversity>=minCultures).sort((a,b)=>b.diversity-a.diversity||b.support-a.support)}
export function contrastMeanings(records:CulturalCorpusRecord[],feature:string){const byCulture=new Map<string,Set<string>>();for(const r of records){if(!r.features.some(f=>f.id===feature||f.value===feature))continue;const s=byCulture.get(r.cultureId)??new Set<string>();r.meanings.forEach(m=>s.add(m));byCulture.set(r.cultureId,s)}return[...byCulture].map(([cultureId,m])=>({cultureId,meanings:[...m]}))}
export function universalVocabulary(invariants:Invariant[]){return invariants.filter(x=>x.sources.length>=2).map((x,i)=>({id:"u-"+String(i+1).padStart(3,"0"),primitive:x.primitive,relation:x.relation,evidence:{cultures:x.cultures,sources:x.sources},semanticAssignment:null as string|null}))}
export function featureCoverage(records:CulturalCorpusRecord[],families:FeatureFamily[]){return families.map(f=>({family:f,cultures:[...new Set(records.filter(r=>r.features.some(x=>x.family===f)).map(r=>r.cultureId))]}))}
