export type FeatureFamily="composition"|"geometry"|"rhythm"|"placement"|"material"|"technique"|"color"|"semantics"|"scale"|"negative-space";
export interface CulturalFeature{id:string;family:FeatureFamily;value:string;weight:number}
export interface CulturalCorpusRecord{id:string;cultureId:string;region:string;tradition:string;period?:string;objectType:string;features:CulturalFeature[];meanings:string[];sourceIds:string[];confidence:number;access:"open-principle"|"review"|"restricted"|"prohibited"}
export interface CulturalProfile{cultureId:string;records:number;features:Record<string,number>;meanings:Record<string,number>;sourceDiversity:number;confidence:number}
const add=(m:Record<string,number>,k:string,n:number)=>m[k]=(m[k]??0)+n;
export function profileCulture(records:CulturalCorpusRecord[],cultureId:string):CulturalProfile{const xs=records.filter(r=>r.cultureId===cultureId&&r.access!=="prohibited"),features:Record<string,number>={},meanings:Record<string,number>={};let conf=0;const sources=new Set<string>();for(const r of xs){conf+=r.confidence;for(const s of r.sourceIds)sources.add(s);for(const f of r.features)add(features,f.family+":"+f.value,f.weight*r.confidence);for(const m of r.meanings)add(meanings,m,r.confidence)}const z=Math.max(1,xs.length);for(const k in features)features[k]/=z;for(const k in meanings)meanings[k]/=z;return{cultureId,records:xs.length,features,meanings,sourceDiversity:sources.size,confidence:conf/z}}
const keys=(a:Record<string,number>,b:Record<string,number>)=>[...new Set([...Object.keys(a),...Object.keys(b)])];
export function cosine(a:Record<string,number>,b:Record<string,number>){let dot=0,aa=0,bb=0;for(const k of keys(a,b)){const x=a[k]??0,y=b[k]??0;dot+=x*y;aa+=x*x;bb+=y*y}return aa&&bb?dot/Math.sqrt(aa*bb):0}
export function compareCultures(records:CulturalCorpusRecord[],aId:string,bId:string){const a=profileCulture(records,aId),b=profileCulture(records,bId),all=keys(a.features,b.features);const distinctiveA=all.map(k=>({feature:k,delta:(a.features[k]??0)-(b.features[k]??0)})).filter(x=>x.delta>.15).sort((x,y)=>y.delta-x.delta).slice(0,20),distinctiveB=all.map(k=>({feature:k,delta:(b.features[k]??0)-(a.features[k]??0)})).filter(x=>x.delta>.15).sort((x,y)=>y.delta-x.delta).slice(0,20),shared=all.map(k=>({feature:k,strength:Math.min(a.features[k]??0,b.features[k]??0)})).filter(x=>x.strength>.12).sort((x,y)=>y.strength-x.strength).slice(0,20);return{a,b,featureSimilarity:cosine(a.features,b.features),semanticSimilarity:cosine(a.meanings,b.meanings),distinctiveA,distinctiveB,shared}}
export function findCorpusGaps(records:CulturalCorpusRecord[],cultureIds:string[],families:FeatureFamily[]){return cultureIds.flatMap(c=>families.map(f=>{const xs=records.filter(r=>r.cultureId===c&&r.features.some(x=>x.family===f));return{cultureId:c,family:f,records:xs.length,sources:new Set(xs.flatMap(x=>x.sourceIds)).size,meanConfidence:xs.length?xs.reduce((n,x)=>n+x.confidence,0)/xs.length:0}})).filter(x=>x.records<3||x.sources<2||x.meanConfidence<.7)}
export function nearestCulturalProfiles(records:CulturalCorpusRecord[],cultureId:string){const a=profileCulture(records,cultureId);return[...new Set(records.map(r=>r.cultureId))].filter(x=>x!==cultureId).map(id=>{const b=profileCulture(records,id);return{cultureId:id,similarity:cosine(a.features,b.features)}}).sort((x,y)=>y.similarity-x.similarity)}
