import type{PatternFragment,PatternInstanceRecord}from"./pattern-fragment-graph";
export interface StructuralLayers{components:PatternFragment[][];junctions:PatternFragment[];repeats:{signature:string;ids:string[]}[];radials:{cx:number;cy:number;ids:string[]}[];voids:{x:number;y:number;radius:number}[];hierarchy:{level:number;ids:string[]}[]}
const dist=(a:any,b:any)=>Math.hypot(a.points[0].x-b.points[0].x,a.points[0].y-b.points[0].y);
export function connectedComponents(fs:PatternFragment[],radius=.035){const unseen=new Set(fs.map(f=>f.id)),by=new Map(fs.map(f=>[f.id,f])),out:PatternFragment[][]=[];while(unseen.size){const first=unseen.values().next().value as string,q=[first],c:PatternFragment[]=[];unseen.delete(first);while(q.length){const id=q.pop()!,f=by.get(id)!;c.push(f);for(const oid of [...unseen])if(dist(f,by.get(oid)!)<=radius){unseen.delete(oid);q.push(oid)}}out.push(c)}return out}
export function detectJunctions(fs:PatternFragment[],radius=.025,minNeighbors=3){return fs.filter(f=>fs.reduce((n,o)=>n+(o.id!==f.id&&dist(f,o)<=radius?1:0),0)>=minNeighbors).map(f=>({...f,kind:"junction" as const,relation:"junction"}))}
export function detectRepeats(fs:PatternFragment[],cell=.08){const m=new Map<string,string[]>();for(const f of fs){const p=f.points[0],sig=`${Math.round(p.x/cell)%4}:${Math.round(p.y/cell)%4}:${Math.round(f.weight*4)}`;m.set(sig,[...(m.get(sig)||[]),f.id])}return[...m].filter(([,ids])=>ids.length>=3).map(([signature,ids])=>({signature,ids}))}
export function detectRadials(fs:PatternFragment[],radius=.12,min=5){const out:{cx:number;cy:number;ids:string[]}[]=[];for(const f of fs){const near=fs.filter(o=>dist(f,o)<=radius);if(near.length>=min)out.push({cx:f.points[0].x,cy:f.points[0].y,ids:near.map(n=>n.id)})}return out.sort((a,b)=>b.ids.length-a.ids.length).slice(0,12)}
export function estimateVoids(fs:PatternFragment[],grid=12){const out:{x:number;y:number;radius:number}[]=[];for(let y=1;y<grid;y++)for(let x=1;x<grid;x++){const p={points:[{x:x/grid,y:y/grid}]};const d=Math.min(...fs.map(f=>dist(p,f)));if(d>.07)out.push({x:x/grid,y:y/grid,radius:d})}return out.sort((a,b)=>b.radius-a.radius).slice(0,24)}
export function buildHierarchy(fs:PatternFragment[],components:PatternFragment[][]){return[{level:0,ids:fs.map(f=>f.id)},{level:1,ids:components.filter(c=>c.length>2).flatMap(c=>c.map(f=>f.id))},{level:2,ids:components.filter(c=>c.length>8).flatMap(c=>c.map(f=>f.id))}]}
export function analyzeStructuralLayers(record:PatternInstanceRecord):StructuralLayers{const f=record.fragments,c=connectedComponents(f);return{components:c,junctions:detectJunctions(f),repeats:detectRepeats(f),radials:detectRadials(f),voids:estimateVoids(f),hierarchy:buildHierarchy(f,c)}}
