import{renderAscendSentence,type AscendSentence}from"./ascend-universal-language";
export interface SkeletonNode{id:string;role:string;x:number;y:number}
export interface SkeletonEdge{from:string;to:string;relation:string;directed:boolean}
export interface SemanticSkeleton{version:"tesseract-skeleton-v1";meaning:string;nodes:SkeletonNode[];edges:SkeletonEdge[];topology:"bilateral"|"branching"|"radial";continuity:"open"|"closed"|"returning";seed:string}
export interface WorkablePattern{skeleton:SemanticSkeleton;svg:string;checksum:string}
const hash=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return(h>>>0).toString(16).padStart(8,"0")};
export function skeletonFromMeaning(meaning:string,seed="tesseract"){const m=meaning.trim().toLowerCase();const love=/love|trust|together/.test(m),ret=/return|home|back/.test(m),grow=/grow|growth|ascent|transform/.test(m);const topology=ret?"radial":grow?"branching":"bilateral";const continuity=ret?"returning":love?"closed":"open";const nodes:SkeletonNode[]=[{id:"speaker",role:"actor",x:.15,y:.5},{id:"junction",role:love?"reciprocity":grow?"growth":"relation",x:.5,y:.5},{id:"target",role:"recipient",x:.85,y:.5}];if(grow)nodes.push({id:"branch",role:"continuation",x:.5,y:.15});const edges:SkeletonEdge[]=[{from:"speaker",to:"junction",relation:love?"approach":"express",directed:true},{from:"junction",to:"target",relation:love?"bind":ret?"return":"continue",directed:true}];if(grow)edges.push({from:"junction",to:"branch",relation:"expand",directed:true});if(ret)edges.push({from:"target",to:"speaker",relation:"return",directed:true});return{version:"tesseract-skeleton-v1" as const,meaning:m,nodes,edges,topology,continuity,seed}}
function sentence(s:SemanticSkeleton):AscendSentence{return{seed:s.seed,meaning:s.meaning,intensity:.75,continuity:s.continuity==="closed"?"enduring":"flowing",reciprocity:s.nodes.some(n=>n.role==="reciprocity")?"mutual":"single",operations:s.edges.map(e=>e.relation) as any,topology:s.topology,closure:s.continuity==="closed"?"closed":"open",rhythm:"steady"}}
export function generateWorkablePattern(meaning:string,seed="tesseract"):WorkablePattern{const skeleton=skeletonFromMeaning(meaning,seed);const payload=JSON.stringify(skeleton);let svg=renderAscendSentence(sentence(skeleton));const metadata=`<metadata id="tesseract-skeleton">${encodeURIComponent(payload)}</metadata>`;svg=svg.replace(/<svg([^>]*)>/,`<svg$1>${metadata}`);return{skeleton,svg,checksum:hash(payload)}}
export function decodeSkeleton(svg:string):SemanticSkeleton{const m=svg.match(/<metadata id="tesseract-skeleton">([^<]+)<\/metadata>/);if(!m)throw new Error("Tesseract skeleton metadata missing");const s=JSON.parse(decodeURIComponent(m[1])) as SemanticSkeleton;if(s.version!=="tesseract-skeleton-v1")throw new Error("Unsupported skeleton version");return s}
export function verifyRoundTrip(p:WorkablePattern){return JSON.stringify(decodeSkeleton(p.svg))===JSON.stringify(p.skeleton)}
