import React,{useMemo,useState} from 'react';
import {BOTANICAL_KINDS,generateUkrainianBotanical,type BotanicalKind} from '../../../packages/tesseract-engine/src/ukrainian-botanical';
import './ornament-studio.css';
const NAMES:Record<BotanicalKind,string>={'flowering-tree':'Flowering tree','curling-vine':'Curling blossom vine','paired-bird-garden':'Paired birds & flowering garden'};
function download(name:string,text:string,type:string){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function BotanicalStudio({onBands,onResearch}:{onBands:()=>void;onResearch:()=>void}){
 const [kind,setKind]=useState<BotanicalKind>('flowering-tree'),[palette,setPalette]=useState<'red-cream'|'garden-dark'>('red-cream'),[tiers,setTiers]=useState<3|4|5>(4),[variation,setVariation]=useState(0);
 const design=useMemo(()=>generateUkrainianBotanical({seed:'botanical-studio:'+variation,kind,palette,tiers}),[kind,palette,tiers,variation]);
 return <main className="ornamentApp"><header className="ornamentHeader"><a className="ornamentWordmark" href="#">ASCEND<span>BOTANICAL ORNAMENT STUDIO</span></a><div><button className="quietButton" onClick={onBands}>Geometric bands</button> <button className="quietButton" onClick={onResearch}>Research</button></div></header>
 <div className="ornamentIntro"><div><span className="ornamentEyebrow">BRANCH · LEAF · BLOSSOM · BORDER</span><h1>A garden in ornament.</h1><p>Layered floral compositions informed by examined Ukrainian rushnyky: branching stems, veined leaves, blossoms and climbing borders.</p></div><span className="prototypeTag">Design prototype</span></div>
 <div className="ornamentWorkspace"><aside className="ornamentControls"><section><h2><b>01</b> Choose a composition</h2><div className="authorFamilies">{BOTANICAL_KINDS.map(k=><button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)}><strong>{NAMES[k]}</strong><small>{k==='flowering-tree'?'Central trunk, paired branches and layered flowers':k==='curling-vine'?'Alternating curls, leaves, buds and blossoms':'Facing birds beneath a flowering tree'}</small></button>)}</div></section>
 <section><h2><b>02</b> Shape the garden</h2><label htmlFor="bot-tiers">Branch tiers</label><select id="bot-tiers" value={tiers} onChange={e=>setTiers(Number(e.target.value) as 3|4|5)}><option value="3">Three · open</option><option value="4">Four · layered</option><option value="5">Five · abundant</option></select><label htmlFor="bot-palette">Palette</label><select id="bot-palette" value={palette} onChange={e=>setPalette(e.target.value as 'red-cream'|'garden-dark')}><option value="red-cream">Crimson on linen</option><option value="garden-dark">Flowers on dark ground</option></select><button className="quietButton fullWidth" onClick={()=>setVariation(v=>v+1)}>Explore another branch construction</button></section>
 <section><h2><b>03</b> Examined references</h2><p>Public Krovets previews show several scales of flowers and branching plant structures. These compositions use independently drawn geometry.</p>{design.metadata.references.map(r=><p key={r.id} style={{fontSize:12}}><a href={r.url} target="_blank" rel="noreferrer">{r.id}</a> — {r.observation}</p>)}</section></aside>
 <section className="ornamentPreview"><div className="previewToolbar"><span>{NAMES[kind]}</span><span>180 × 250 mm</span></div><div style={{background:'#eae3d6',padding:20,display:'flex',justifyContent:'center'}}><div className="botanicalArtwork" style={{width:'100%',maxWidth:580,aspectRatio:'180/250'}} dangerouslySetInnerHTML={{__html:design.svg}}/></div><div className="authorReview"><h2>Your botanical composition</h2><p>Flowers contain two petal layers and fine centres; branches carry leaves, buds and smaller blossoms. The vine frame echoes the main field. SVG and fill plan share the same geometry.</p><div className="reviewActions"><button className="primaryButton" onClick={()=>download(kind+'.svg',design.svg,'image/svg+xml')}>Download SVG</button><button className="quietButton" onClick={()=>download(kind+'-plan.json',JSON.stringify({units:'mm',widthMm:design.widthMm,heightMm:design.heightMm,sourceEvidence:design.metadata,objects:design.objects},null,2),'application/json')}>Download design plan</button></div><p style={{fontSize:12}}>New compositions, not historical reproductions. Textile production requires digitisation and a physical sample.</p></div></section></div></main>;
}
