import React,{useEffect,useRef}from"react";import * as THREE from"three";import{GarmentView,Placement}from"./configurator-model";import{generatePatternSvg}from"./pattern-catalog";
const rot:Record<GarmentView,number>={front:0,left:Math.PI/2,back:Math.PI,right:-Math.PI/2};
export function GarmentViewer({view,placement,patternId,fabric,onZone}:{view:GarmentView;placement:Placement;patternId:string;fabric:string;onZone:(p:Placement)=>void}){const host=useRef<HTMLDivElement>(null);useEffect(()=>{if(!host.current)return;const el=host.current,scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(32,1,.1,100);camera.position.set(0,.2,7);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.replaceChildren(renderer.domElement);const group=new THREE.Group();scene.add(group);
const cloth=new THREE.MeshStandardMaterial({color:fabric==="black"?0x252421:fabric==="navy"?0x26303c:fabric==="sand"?0xcbbda5:0xe9e0d1,roughness:.92,metalness:0,side:THREE.DoubleSide});
const torso=new THREE.Mesh(new THREE.CapsuleGeometry(1.28,2.15,8,24),cloth);torso.scale.set(1,.95,.34);group.add(torso);
const sleeveGeo=new THREE.CylinderGeometry(.38,.27,2.25,24,1,true);for(const side of[-1,1]){const s=new THREE.Mesh(sleeveGeo,cloth);s.position.set(side*1.55,.45,0);s.rotation.z=side*.43;group.add(s)}
const collar=new THREE.Mesh(new THREE.TorusGeometry(.48,.09,10,32,Math.PI*1.55),cloth);collar.position.set(0,1.7,.28);collar.rotation.x=Math.PI/2;group.add(collar);
const svg=generatePatternSvg(patternId,"ascend-webgl-v1"),url="data:image/svg+xml;charset=utf-8,"+encodeURIComponent(svg),loader=new THREE.TextureLoader();loader.load(url,tex=>{tex.colorSpace=THREE.SRGBColorSpace;const mat=new THREE.MeshBasicMaterial({map:tex,transparent:true,side:THREE.DoubleSide,depthWrite:false});const zone=placement.includes("sleeve")||placement.includes("cuff")?new THREE.PlaneGeometry(.75,1.75):new THREE.PlaneGeometry(1.65,.48),m=new THREE.Mesh(zone,mat);m.position.set(placement.startsWith("left")?-1.58:placement.startsWith("right")?1.58:0,placement.includes("cuff")?-.25:placement.includes("sleeve")?.55:placement==="collar"?1.42:placement==="hem"?-1.45:.45,.48);if(placement.includes("left"))m.rotation.z=.43;if(placement.includes("right"))m.rotation.z=-.43;group.add(m)});
scene.add(new THREE.HemisphereLight(0xffffff,0x777777,2.4));const key=new THREE.DirectionalLight(0xffffff,2.2);key.position.set(3,4,5);scene.add(key);let drag=false,last=0;renderer.domElement.onpointerdown=e=>{drag=true;last=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)};renderer.domElement.onpointermove=e=>{if(drag){group.rotation.y+=(e.clientX-last)*.012;last=e.clientX}};renderer.domElement.onpointerup=()=>drag=false;group.rotation.y=rot[view];
const resize=()=>{const w=el.clientWidth,h=Math.max(420,el.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(el);let id=0;const loop=()=>{renderer.render(scene,camera);id=requestAnimationFrame(loop)};loop();return()=>{cancelAnimationFrame(id);ro.disconnect();renderer.dispose();el.replaceChildren()};},[view,placement,patternId,fabric]);return <div className="webglGarment"><div ref={host} className="webglCanvas"/><div className="viewLabel">REAL-TIME 3D · drag to rotate · {view.toUpperCase()}</div><button className="zoneCycle" onClick={()=>onZone(placement)}>Pattern: {placement.replace("-"," ")}</button></div>}
