import React,{useMemo,useState} from "react";
import {generateUkrainianBand,UKRAINIAN_BAND_SOURCE,UKRAINIAN_BAND_KINDS,type UkrainianBandKind} from "../../../packages/tesseract-engine/src/ukrainian-band";
import "./ornament-studio.css";
const NAMES:Record<UkrainianBandKind,string>={"stepped-cross":"Stepped cross & diamond","diamond-rosette":"Diamond & eight-point centre","linked-diamonds":"Linked diamond lattice","hooked-medallions":"Hooked four-part medallions","joined-diamond-network":"Joined diamond network"};
function download(name:string,text:string,type:string){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
export default function UkrainianStudio({onResearch}:{onResearch:()=>void}){
 const [kind,setKind]=useState<UkrainianBandKind>("hooked-medallions"),[repeats,setRepeats]=useState(11),[bands,setBands]=useState<1|3|5>(3),[palette,setPalette]=useState<"hutsul"|"red-black">("hutsul"),[variation,setVariation]=useState(0),[placement,setPlacement]=useState<"cuff"|"collar">("cuff");
 const widthMm=placement==="cuff"?250:360,heightMm=placement==="cuff"?60:50;
 const band=useMemo(()=>generateUkrainianBand({seed:"ukrainian-studio:"+variation,kind,widthMm,heightMm,repeats,palette,bands}),[variation,kind,widthMm,heightMm,repeats,palette,bands]);
 const source=UKRAINIAN_BAND_SOURCE.source;
 return <main className="ornamentApp"><header className="ornamentHeader"><a className="ornamentWordmark" href="#">ASCEND<span>UKRAINIAN ORNAMENT STUDIO</span></a><button className="quietButton" onClick={onResearch}>Research & generated runs</button></header>
 <div className="ornamentIntro"><div><span className="ornamentEyebrow">COUNTED CELLS · REPEAT · BORDER</span><h1>Ukrainian embroidery rhythm.</h1><p>Geometric bands informed by an examined Ukrainian plate and a study of Western Ukrainian woven sashes.</p></div><span className="prototypeTag">Design prototype</span></div>
 <div className="ornamentWorkspace"><aside className="ornamentControls">
 <section><h2><b>01</b> Choose the band</h2><div className="authorFamilies">{UKRAINIAN_BAND_KINDS.map(k=><button key={k} aria-pressed={kind===k} onClick={()=>setKind(k)}><span className="familyArtwork" dangerouslySetInnerHTML={{__html:generateUkrainianBand({seed:"preview",kind:k,widthMm:250,heightMm:60,repeats:6,palette}).svg}}/><strong>{NAMES[k]}</strong><small>Nested figures, joined repeats and related borders</small></button>)}</div></section>
 <section><h2><b>02</b> Compose the repeat</h2><label htmlFor="uk-placement">Artwork placement</label><select id="uk-placement" value={placement} onChange={e=>{const p=e.target.value as "cuff"|"collar";setPlacement(p);setRepeats(Math.max(3,Math.min(24,Math.round((p==="cuff"?250/60:360/50)*(bands===1?35:bands===3?65:87)/25))));}}><option value="cuff">Cuff band · 250 × 60 mm</option><option value="collar">Collar band · 360 × 50 mm</option></select><label htmlFor="uk-bands">Composition</label><select id="uk-bands" value={bands} onChange={e=>{const n=Number(e.target.value) as 1|3|5;setBands(n);setRepeats(Math.max(3,Math.min(24,Math.round(widthMm/heightMm*(n===1?35:n===3?65:87)/25))));}}><option value="1">One framed motif row</option><option value="3">Three bands · larger centre, paired flanks</option><option value="5">Five bands · centre, flanks & fine edges</option></select><label htmlFor="uk-repeat">Repeat units <output>{repeats}</output></label><input id="uk-repeat" type="range" min="3" max="24" value={repeats} onChange={e=>setRepeats(Number(e.target.value))}/><label htmlFor="uk-palette">Thread palette</label><select id="uk-palette" value={palette} onChange={e=>setPalette(e.target.value as "hutsul"|"red-black")}><option value="hutsul">Red, black, yellow & green</option><option value="red-black">Red & black</option></select><button className="quietButton fullWidth" onClick={()=>setVariation(v=>v+1)}>{kind==="hooked-medallions"||kind==="joined-diamond-network"?"Explore another construction":"Alternate the internal colours"}</button></section>
 <section><h2><b>03</b> Examined source</h2><p style={{fontSize:12,lineHeight:1.6}}>The reference plate uses nested diamonds, stepped centres, contrasting cells and narrow framing bands. These new designs use that construction hierarchy.</p><a href={source.source_url} target="_blank" rel="noreferrer">{source.title}</a><p style={{fontSize:11}}>Neon record: {source.id}<br/>One reviewed image · regional authenticity unverified</p><p style={{fontSize:11,lineHeight:1.6}}>Three- and five-band hierarchy follows the supplied sash paper, pp. 1154–1158. Exact band widths are design choices.</p><a href="https://doi.org/10.15407/nz2022.05.1147" target="_blank" rel="noreferrer">Nykorak, Herus & Kutsyr (2022)</a></section>
 </aside><section className="ornamentPreview"><div className="previewToolbar"><span>{NAMES[kind]}</span><span>Exact shared geometry</span></div><div className="authorProductStage" style={{minHeight:320,background:"#f6f0df"}}><div className="exactArtwork" style={{aspectRatio:String(widthMm/heightMm),padding:0,minWidth:0,minHeight:0,maxWidth:"100%"}} dangerouslySetInnerHTML={{__html:band.svg}}/></div><div className="artworkDimensions"><strong>{widthMm} × {heightMm} mm</strong><span>Design cell {band.metadata.cellSizeMm.x.toFixed(2)} × {band.metadata.cellSizeMm.y.toFixed(2)} mm · {Math.round(band.metadata.ornamentCoverage*100)}% ornament cells</span></div><div className="authorReview"><h2>Your Ukrainian band</h2><p>SVG and fill-plan export share the same geometry and colours. These are new source-informed constructions, not a traditional motif reproduction. Embroidery digitisation and a physical sew-out are required before production.</p><div className="reviewActions"><button className="primaryButton" onClick={()=>download(kind+".svg",band.svg,"image/svg+xml")}>Download SVG</button><button className="quietButton" onClick={()=>download(kind+"-specification.json",JSON.stringify({units:"mm",widthMm,heightMm,palette:band.palette,sourceEvidence:band.metadata,source:UKRAINIAN_BAND_SOURCE,objects:band.objects},null,2),"application/json")}>Download design & fill plan</button></div><details><summary>What informs this design</summary><p>Visually reviewed source structure and a versioned snapshot of its Neon analysis. No claim that all Ukraine-labelled records have been examined or used. This is rule-based composition, not an ML motif-recognition model.</p><code>{band.metadata.conditioning}</code></details></div></section></div>
 <footer className="ornamentFooter">Composition approach informed by <a href="https://vytvory.ua/uk/about" target="_blank" rel="noreferrer">Vytvory</a> · Source review and exports are traceable</footer></main>;
}
