/**
 * First sew-out pack: everything an embroiderer needs for the first physical test, in one folder.
 *
 *   npx tsx scripts/originals/sewout-pack.mts [out-dir=originals/sewout-pack-01]
 *
 *   01-calibration       stitch calibration strip + measurement sheet (turns the linen recipe into a validated one)
 *   02-cuff-band         "Ascend Roots" rich folk band (tree of life, birds, kalyna), 250 × 60 mm
 *   03-hidden-message    one full repeat of the sprig band carrying «Сила роду — у нитці», read by the phone reader
 *
 * Every design here has passed the stitch gate (except the calibration strip's deliberate limit tests), and the
 * hidden-message band verifies itself by decoding its own stitch preview before the pack is written.
 * No visible codes: the message lives only in the ornament.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

const out = process.argv[2] ?? "originals/sewout-pack-01";
const tsx = (args: string[]) => execFileSync("npx", ["tsx", ...args], { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] });
const dir = (d: string) => { const p = join(out, d); mkdirSync(p, { recursive: true }); return p; };

// 01 calibration strip
const cal = JSON.parse(tsx(["packages/stitch-engine/src/calibration-cli.ts", dir("01-calibration")]).trim().split("\n").pop()!);

// 02 cuff band (generated by rich-bands.mts; the board-colour DST and its stitch preview)
const d2 = dir("02-cuff-band");
for (const f of ["01-ascend-roots.dst", "01-ascend-roots-board.svg", "01-ascend-roots-stitches.svg"]) copyFileSync(join("originals/designs/rich-bands", f), join(d2, f));
const cuff = (JSON.parse(readFileSync("originals/designs/rich-bands/bands-board.json", "utf8")) as any[]).find((b) => b.id === "01-ascend-roots");

// 03 hidden message: one full repeat plus its marker (fits a 360 × 100 border frame)
const msg = JSON.parse(tsx(["scripts/originals/ornament-message-band.mts", dir("03-hidden-message"), "Сила роду — у нитці", "340"]));
if (!msg.verified) throw new Error("hidden-message band did not verify");

const extentText = (e: any) => Array.isArray(e) ? e.map((v: number) => Math.round(v)).join(" × ") : e && typeof e === "object" ? Object.values(e).map((v: any) => Math.round(Number(v))).join(" × ") : "≤ 200 × 200";
const row = (n: string, file: string, size: string, st: number, min: number, col: number, hoop: string) => `| ${n} | \`${file}\` | ${size} | ${st.toLocaleString("en")} | ${min} | ${col} | ${hoop} |`;
const readme = `# ASCEND first sew-out pack

Three pieces for the first physical test on the shirt linen. Everything here is a prototype until this sew-out is
measured: the linen recipe is a starting point, and this test is what validates it.

| # | Machine file | Size (mm) | Stitches | Minutes* | Colours | Hoop |
|---|---|---|---|---|---|---|
${row("01 Calibration strip", "01-calibration/ascend-calibration-linen-180-prewashed.dst", extentText(cal.extent), cal.stitches, cal.minutes, Array.isArray(cal.colors) ? cal.colors.length : 2, "200 × 200")}
${row("02 Cuff band «Ascend Roots»", "02-cuff-band/01-ascend-roots.dst", "250 × 60", cuff.stitches, cuff.minutes, cuff.colors, "border frame ≥ 260 × 70")}
${row("03 Hidden message band", "03-hidden-message/band.dst", `${msg.sizeMm.join(" × ")}`, msg.stitches, msg.minutes, msg.colors, "border frame 360 × 100")}

*at 650 stitches/min, before trims and colour changes.

## Materials

- **Fabric:** the shirt linen, about 180 g/m², **pre-washed** (wash and press before hooping, so shrinkage is measured, not sewn in).
- **Stabiliser:** medium cut-away under everything; tear-away is too weak for the fills on linen.
- **Thread:** 40 wt polyester or rayon. Colours are in each preview; the reader needs good contrast with the linen
  (blue star, green leaves, orange/red buds for piece 03).
- **Needle:** 75/11 sharp.

## Sew order

1. **01 Calibration strip** first. Fill in \`01-calibration/*.measurements.csv\` (after stitching, then again after one wash).
   The 0.8 mm satin, 0.35/0.38 mm fills and the 0.5 mm gap are deliberate limit tests: they are expected to look marginal.
2. **03 Hidden message band.** Then open the reader on a phone (\`https://ascend-glyph-studio.onrender.com/reader/\`, once online,
   afterwards it works offline), hold the band level in the box and sweep slowly, or use “Take a photo”.
3. **02 Cuff band**, the visual piece.

## Send back

- Photos of each piece in daylight, straight on, with a ruler in frame; a close-up of any puckering, gaps or thread breaks.
- The completed measurements CSV.
- Whether the reader worked, how close/far the phone was, and how many photos the reader needed.
- The same after one wash at 40 °C.

These results update the linen recipe (pull compensation, density, minimum gaps) and turn the production gate from
“prototype” into “validated”.
`;
writeFileSync(join(out, "README.md"), readme);
console.log(JSON.stringify({ out, calibration: cal, cuff: { stitches: cuff.stitches, minutes: cuff.minutes }, message: { verified: msg.verified, size: msg.sizeMm } }));
