import "./style.css"; import {loadProducts,createCart,shopifyReady,domain} from "./shopify.js";
const fallback=[
 {id:"earth",title:"Earth — Foundation Shirt",description:"A quiet linen field with a canonical Earth glyph border.",priceRange:{minVariantPrice:{amount:"0",currencyCode:"USD"}},featuredImage:null,variants:{nodes:[]}},
 {id:"fire",title:"Fire — Rising Shirt",description:"Structured repetition built from the Fire family.",priceRange:{minVariantPrice:{amount:"0",currencyCode:"USD"}},featuredImage:null,variants:{nodes:[]}},
 {id:"object",title:"108 Keys Notebook",description:"A restrained object carrying the ASCEND symbolic language.",priceRange:{minVariantPrice:{amount:"0",currencyCode:"USD"}},featuredImage:null,variants:{nodes:[]}}
];
const app=document.querySelector("#app");
app.innerHTML=`<header><a class="brand" href="#">ASCEND <span>OBJECTS</span></a><nav><a href="#shop">Shop</a><a href="#language">Glyph Language</a><button id="bag">Bag <b>0</b></button></nav></header>
<main><section class="hero"><div class="eyebrow">108 KEYS · FIVE FAMILIES · ONE LANGUAGE</div><h1>Wear the<br><em>language.</em></h1><p>ASCEND Objects turns the 108 Keys into a living design system — glyphs repeated, mirrored and composed into garments and objects with meaning.</p><a class="cta" href="#shop">Enter the collection <span>↘</span></a><div class="sigil" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div></section>
<section id="language" class="language"><p>THE SYSTEM</p><h2>Not decoration.<br>A symbolic grammar.</h2><div class="families">${["EARTH","WATER","FIRE","AIR","SPIRIT"].map((x,i)=>`<article><span>0${i+1}</span><div class="mark m${i}">◇</div><h3>${x}</h3></article>`).join("")}</div></section>
<section id="shop" class="shop"><div class="sectionhead"><div><p>THE FIRST EDIT</p><h2>Objects with intention.</h2></div><span id="status">Connecting to Shopify…</span></div><div class="grid" id="products"></div></section>
<section class="manifesto"><div>ASCEND / 108</div><blockquote>“The glyphs are the language.<br>The object is the canvas.”</blockquote><p>Designed from the canonical ASCEND system.<br>Built for repetition, ritual and everyday use.</p></section></main>
<footer><div class="brand">ASCEND <span>OBJECTS</span></div><p>Portland, Oregon · Five families · 108 Keys</p><a href="https://${domain}" target="_blank" rel="noreferrer">Shopify checkout ↗</a></footer>`;
function money(p){const n=Number(p?.amount||0);return n?new Intl.NumberFormat("en-US",{style:"currency",currency:p.currencyCode||"USD"}).format(n):"Coming soon"}
function card(p){const img=p.featuredImage?.url?`<img src="${p.featuredImage.url}" alt="${p.featuredImage.altText||p.title}">`:`<div class="glyphart"><span>⌁</span><b>ASCEND</b></div>`;return `<article class="product">${img}<div class="productcopy"><div><h3>${p.title}</h3><p>${p.description||""}</p></div><div class="buy"><span>${money(p.priceRange?.minVariantPrice)}</span>${p.variants?.nodes?.[0]?`<button data-variant="${p.variants.nodes[0].id}">Buy</button>`:""}</div></div></article>`}
async function init(){let products=fallback;const status=document.querySelector("#status");try{if(shopifyReady){products=await loadProducts();status.textContent=`${products.length} products · live from Shopify`}else status.textContent="Shopify catalog ready to connect";}catch(e){status.textContent="Shopify connection pending";}document.querySelector("#products").innerHTML=products.map(card).join("");document.querySelectorAll("[data-variant]").forEach(btn=>btn.onclick=async()=>{const old=btn.textContent;btn.textContent="Opening…";btn.disabled=true;try{const cart=await createCart(btn.dataset.variant);window.location.href=cart.checkoutUrl}catch(e){btn.textContent="Try again";setTimeout(()=>{btn.textContent=old;btn.disabled=false},1500)}})}init();